env:
  node: true
  jest: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'backend/tsconfig.json'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import/typescript
rules:
  newline-before-return: error
  quotes:
    - error
    - double
  semi:
    - off
